name: flutter_todo_list
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  msh_checkbox: ^2.0.1 
  uuid: ^4.5.1
  cupertino_icons: ^1.0.2
  firebase_core: ^3.9.0
  firebase_database: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
